# Generated by Django 5.1 on 2024-09-09 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precise_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='bath',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='bed',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='frequency',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='pets',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sqft',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
