# Generated by Django 5.1 on 2024-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precise_detail', '0002_alter_estimate_bath_alter_estimate_bed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='first',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='last',
        ),
        migrations.AddField(
            model_name='estimate',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='estimate',
            name='name',
            field=models.CharField(default='unknown', max_length=100),
        ),
    ]
