# Generated by Django 5.1 on 2024-09-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('precise_detail', '0003_remove_estimate_first_remove_estimate_last_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='zip',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
